### ISSUE TITLE
Test-Case Question About Project2

### ISSUE THREAD

**Issue by Certseeds** [sqlab-sustech/CS323-Compilers#5]
I Have a question:
in the material of project2: [test_2_o01.spl](https://github.com/sqlab-sustech/CS323-Compilers/blob/master/project2/test/test_2_o01.spl)
there exists a function
``` c
int test_2_o01(int a, int b)
{
  int c;
  c = foo();
  if (b > 0)
  {
    int a = c + 3;
    b = b - a;
  }
  a = a + b;
  return a;
}
```
in this function's params definition, there exist a variable named `a`,
but in the if-statement there also define a variable which name is `a`,
Based on `Assumption 6: there are only global scope, i.e., all variable names are unique`
and Errors include `Type 3: variable is redefined in the same scope `, a variable cannot be defined twice even it's one of them are params and the other is normal variable.
Is there anyone can analysis it?
@CirQ @echohermion @Jiachen-Zhang

**Comment by CirQ** [comment]
Actually this test case assume not only global scope. You may see there's an 'o' in the filename, which stands for 'optional'.
However, even this test case is designed for scope checking, I still think it's not a good example. Sorry for causing confusion.
