### ISSUE TITLE
Question About Desciption of Project2

### ISSUE THREAD

**Issue by Certseeds** [sqlab-sustech/CS323-Compilers#6]
In description of Project2, I found a paragraph:
> which generates the semantic analyzer executable. Then we run it by:
bin/splc test/test_2_r01.spl
The analyzer should output the error message in a text file test/test_2_r01.out, if any
semantic error is presented. If no error, touch an empty file.

what does that mean? should the `splc` touch the file by itself?
we usually use `bin/splc test/test_2_r01.spl > test/test_2_r01.out` to do that, instead of "The analyzer touch an empty file".

what's your idea?
@CirQ

**Comment by CirQ** [comment]
Actually both are acceptable in grading, although the documented way is preferable.
